import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS,
  PROJECT_STEPS
} from '../../../../common/constants/projects.js'

// Payload level mappings for API submission
export const PAYLOAD_LEVEL_MAP = {
  [PROJECT_STEPS.NFM_INCLUSION]: PROJECT_PAYLOAD_LEVELS.NFM_INCLUSION,
  [PROJECT_STEPS.NFM_SELECTED_MEASURES]:
    PROJECT_PAYLOAD_LEVELS.NFM_SELECTED_MEASURES,
  [PROJECT_STEPS.NFM_RIVER_RESTORATION]:
    PROJECT_PAYLOAD_LEVELS.NFM_RIVER_RESTORATION,
  [PROJECT_STEPS.NFM_LEAKY_BARRIERS]: PROJECT_PAYLOAD_LEVELS.NFM_LEAKY_BARRIERS,
  [PROJECT_STEPS.NFM_OFFLINE_STORAGE]:
    PROJECT_PAYLOAD_LEVELS.NFM_OFFLINE_STORAGE,
  [PROJECT_STEPS.NFM_WOODLAND]: PROJECT_PAYLOAD_LEVELS.NFM_WOODLAND,
  [PROJECT_STEPS.NFM_HEADWATER_DRAINAGE]:
    PROJECT_PAYLOAD_LEVELS.NFM_HEADWATER_DRAINAGE,
  [PROJECT_STEPS.NFM_RUNOFF_MANAGEMENT]:
    PROJECT_PAYLOAD_LEVELS.NFM_RUNOFF_MANAGEMENT,
  [PROJECT_STEPS.NFM_SALTMARSH]: PROJECT_PAYLOAD_LEVELS.NFM_SALTMARSH,
  [PROJECT_STEPS.NFM_SAND_DUNE]: PROJECT_PAYLOAD_LEVELS.NFM_SAND_DUNE,
  [PROJECT_STEPS.NFM_LAND_USE_CHANGE]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_CHANGE,
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND,
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND,
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND,
  [PROJECT_STEPS.NFM_LAND_USE_SEMI_NATURAL_GRASSLAND]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_SEMI_NATURAL_GRASSLAND,
  [PROJECT_STEPS.NFM_LAND_USE_WOODLAND]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_WOODLAND,
  [PROJECT_STEPS.NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH,
  [PROJECT_STEPS.NFM_LAND_USE_PEATLAND_RESTORATION]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_PEATLAND_RESTORATION,
  [PROJECT_STEPS.NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER,
  [PROJECT_STEPS.NFM_LAND_USE_COASTAL_MARGINS]:
    PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_COASTAL_MARGINS,
  [PROJECT_STEPS.NFM_LANDOWNER_CONSENT]:
    PROJECT_PAYLOAD_LEVELS.NFM_LANDOWNER_CONSENT,
  [PROJECT_STEPS.NFM_EXPERIENCE]: PROJECT_PAYLOAD_LEVELS.NFM_EXPERIENCE_LEVEL,
  [PROJECT_STEPS.NFM_PROJECT_READINESS]:
    PROJECT_PAYLOAD_LEVELS.NFM_PROJECT_READINESS
}

/**
 * Maps each land-use detail step to its before/after field names
 * Used by the generic land-use-detail template
 */
export const LAND_USE_DETAIL_FIELD_CONFIG = {
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND]: {
    beforeFieldName:
      PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND]: {
    beforeFieldName:
      PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_SEMI_NATURAL_GRASSLAND]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_WOODLAND]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_PEATLAND_RESTORATION]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER]: {
    beforeFieldName:
      PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_AFTER
  },
  [PROJECT_STEPS.NFM_LAND_USE_COASTAL_MARGINS]: {
    beforeFieldName: PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_BEFORE,
    afterFieldName: PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_AFTER
  }
}
