import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS
} from '../../../../../common/constants/projects.js'

/**
 * Core project fields payload level mappings
 * Includes: initial save, name, type, financial years
 */
export const CORE_PAYLOAD_LEVEL_FIELDS = {
  [PROJECT_PAYLOAD_LEVELS.INITIAL_SAVE]: [
    PROJECT_PAYLOAD_FIELDS.NAME,
    PROJECT_PAYLOAD_FIELDS.AREA_ID,
    PROJECT_PAYLOAD_FIELDS.PROJECT_TYPE,
    PROJECT_PAYLOAD_FIELDS.PROJECT_INTERVENTION_TYPES,
    PROJECT_PAYLOAD_FIELDS.MAIN_INTERVENTION_TYPE,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_START_YEAR,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_END_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.PROJECT_NAME]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NAME
  ],
  [PROJECT_PAYLOAD_LEVELS.PROJECT_TYPE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.PROJECT_TYPE,
    PROJECT_PAYLOAD_FIELDS.PROJECT_INTERVENTION_TYPES,
    PROJECT_PAYLOAD_FIELDS.MAIN_INTERVENTION_TYPE
  ],
  [PROJECT_PAYLOAD_LEVELS.FINANCIAL_START_YEAR]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_START_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.FINANCIAL_END_YEAR]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_END_YEAR
  ]
}
