import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS
} from '../../../../../common/constants/projects.js'
/**
 * NFM payload level mappings
 */
export const NFM_PAYLOAD_LEVEL_FIELDS = {
  [PROJECT_PAYLOAD_LEVELS.NFM_SELECTED_MEASURES]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_SELECTED_MEASURES,
    // Include all measure data fields so they can be cleared when measures are unselected
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_WIDTH,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_HEADWATER_DRAINAGE_AREA
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_RIVER_RESTORATION]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_VOLUME
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LEAKY_BARRIERS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_WIDTH
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_OFFLINE_STORAGE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_VOLUME
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_WOODLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_AREA
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_HEADWATER_DRAINAGE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_HEADWATER_DRAINAGE_AREA
  ]
}
