import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS
} from '../../../../../common/constants/projects.js'
/**
 * NFM payload level mappings
 */
export const NFM_PAYLOAD_LEVEL_FIELDS = {
  [PROJECT_PAYLOAD_LEVELS.NFM_SELECTED_MEASURES]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_SELECTED_MEASURES,
    // Include all measure data fields so they can be cleared when measures are unselected
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_WIDTH,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_HEADWATER_DRAINAGE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RUNOFF_MANAGEMENT_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RUNOFF_MANAGEMENT_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_SALTMARSH_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_SALTMARSH_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_SAND_DUNE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_SAND_DUNE_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_LAND_USE_CHANGE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_RIVER_RESTORATION]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVER_RESTORATION_VOLUME
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LEAKY_BARRIERS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_VOLUME,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_LENGTH,
    PROJECT_PAYLOAD_FIELDS.NFM_LEAKY_BARRIERS_WIDTH
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_OFFLINE_STORAGE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_OFFLINE_STORAGE_VOLUME
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_WOODLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_AREA
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_HEADWATER_DRAINAGE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_HEADWATER_DRAINAGE_AREA
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_RUNOFF_MANAGEMENT]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_RUNOFF_MANAGEMENT_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_RUNOFF_MANAGEMENT_VOLUME
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_SALTMARSH]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_SALTMARSH_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_SALTMARSH_LENGTH
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_SAND_DUNE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_SAND_DUNE_AREA,
    PROJECT_PAYLOAD_FIELDS.NFM_SAND_DUNE_LENGTH
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_CHANGE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_LAND_USE_CHANGE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_AFTER,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_ARABLE_FARMLAND_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_LIVESTOCK_FARMLAND_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_ENCLOSED_DAIRYING_FARMLAND_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_SEMI_NATURAL_GRASSLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_SEMI_NATURAL_GRASSLAND_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_WOODLAND]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_WOODLAND_LAND_USE_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_MOUNTAIN_MOORS_AND_HEATH_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_PEATLAND_RESTORATION]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_PEATLAND_RESTORATION_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_RIVERS_WETLANDS_FRESHWATER_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LAND_USE_COASTAL_MARGINS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_BEFORE,
    PROJECT_PAYLOAD_FIELDS.NFM_COASTAL_MARGINS_AFTER
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_LANDOWNER_CONSENT]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_LANDOWNER_CONSENT
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_EXPERIENCE_LEVEL]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_EXPERIENCE_LEVEL
  ],
  [PROJECT_PAYLOAD_LEVELS.NFM_PROJECT_READINESS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NFM_PROJECT_READINESS
  ]
}
