import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS
} from '../../../../../common/constants/projects.js'

/**
 * Whole Life Cost payload level mapping.
 * All four WLC cost fields are included for the single WHOLE_LIFE_COST level.
 */
export const WLC_PAYLOAD_LEVEL_FIELDS = {
  [PROJECT_PAYLOAD_LEVELS.WHOLE_LIFE_COST]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.WLC_ESTIMATED_WHOLE_LIFE_PV_COSTS,
    PROJECT_PAYLOAD_FIELDS.WLC_ESTIMATED_DESIGN_CONSTRUCTION_COSTS,
    PROJECT_PAYLOAD_FIELDS.WLC_ESTIMATED_RISK_CONTINGENCY_COSTS,
    PROJECT_PAYLOAD_FIELDS.WLC_ESTIMATED_FUTURE_COSTS
  ]
}
