import {
  PROJECT_PAYLOAD_FIELDS,
  PROJECT_PAYLOAD_LEVELS
} from '../../../../common/constants/projects.js'

/**
 * Mapping of payload levels to their required fields for API submission
 */
export const PROJECT_PAYLOAD_LEVEL_FIELDS = {
  [PROJECT_PAYLOAD_LEVELS.INITIAL_SAVE]: [
    PROJECT_PAYLOAD_FIELDS.NAME,
    PROJECT_PAYLOAD_FIELDS.AREA_ID,
    PROJECT_PAYLOAD_FIELDS.PROJECT_TYPE,
    PROJECT_PAYLOAD_FIELDS.PROJECT_INTERVENTION_TYPES,
    PROJECT_PAYLOAD_FIELDS.MAIN_INTERVENTION_TYPE,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_START_YEAR,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_END_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.PROJECT_NAME]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NAME
  ],
  [PROJECT_PAYLOAD_LEVELS.PROJECT_TYPE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.PROJECT_TYPE,
    PROJECT_PAYLOAD_FIELDS.PROJECT_INTERVENTION_TYPES,
    PROJECT_PAYLOAD_FIELDS.MAIN_INTERVENTION_TYPE
  ],
  [PROJECT_PAYLOAD_LEVELS.FINANCIAL_START_YEAR]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_START_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.FINANCIAL_END_YEAR]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.FINANCIAL_END_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.START_OUTLINE_BUSINESS_CASE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.START_OUTLINE_BUSINESS_CASE_MONTH,
    PROJECT_PAYLOAD_FIELDS.START_OUTLINE_BUSINESS_CASE_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.COMPLETE_OUTLINE_BUSINESS_CASE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.START_OUTLINE_BUSINESS_CASE_MONTH,
    PROJECT_PAYLOAD_FIELDS.START_OUTLINE_BUSINESS_CASE_YEAR,
    PROJECT_PAYLOAD_FIELDS.COMPLETE_OUTLINE_BUSINESS_CASE_MONTH,
    PROJECT_PAYLOAD_FIELDS.COMPLETE_OUTLINE_BUSINESS_CASE_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.AWARD_MAIN_CONTRACT]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.COMPLETE_OUTLINE_BUSINESS_CASE_MONTH,
    PROJECT_PAYLOAD_FIELDS.COMPLETE_OUTLINE_BUSINESS_CASE_YEAR,
    PROJECT_PAYLOAD_FIELDS.AWARD_CONTRACT_MONTH,
    PROJECT_PAYLOAD_FIELDS.AWARD_CONTRACT_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.START_WORK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.AWARD_CONTRACT_MONTH,
    PROJECT_PAYLOAD_FIELDS.AWARD_CONTRACT_YEAR,
    PROJECT_PAYLOAD_FIELDS.START_CONSTRUCTION_MONTH,
    PROJECT_PAYLOAD_FIELDS.START_CONSTRUCTION_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.START_BENEFITS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.START_CONSTRUCTION_MONTH,
    PROJECT_PAYLOAD_FIELDS.START_CONSTRUCTION_YEAR,
    PROJECT_PAYLOAD_FIELDS.READY_FOR_SERVICE_MONTH,
    PROJECT_PAYLOAD_FIELDS.READY_FOR_SERVICE_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.COULD_START_EARLY]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.COULD_START_EARLY
  ],
  [PROJECT_PAYLOAD_LEVELS.EARLIEST_START_DATE]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.COULD_START_EARLY,
    PROJECT_PAYLOAD_FIELDS.EARLIEST_WITH_GIA_MONTH,
    PROJECT_PAYLOAD_FIELDS.EARLIEST_WITH_GIA_YEAR
  ],
  [PROJECT_PAYLOAD_LEVELS.RISK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.RISKS,
    // Include property fields so they can be cleared when risks change
    PROJECT_PAYLOAD_FIELDS.NO_PROPERTIES_AT_RISK,
    PROJECT_PAYLOAD_FIELDS.MAINTAINING_EXISTING_ASSETS,
    PROJECT_PAYLOAD_FIELDS.REDUCING_FLOOD_RISK_50_PLUS,
    PROJECT_PAYLOAD_FIELDS.REDUCING_FLOOD_RISK_LESS_50,
    PROJECT_PAYLOAD_FIELDS.INCREASING_FLOOD_RESILIENCE,
    PROJECT_PAYLOAD_FIELDS.NO_PROPERTIES_AT_COASTAL_EROSION_RISK,
    PROJECT_PAYLOAD_FIELDS.PROPERTIES_BENEFIT_MAINTAINING_ASSETS_COASTAL,
    PROJECT_PAYLOAD_FIELDS.PROPERTIES_BENEFIT_INVESTMENT_COASTAL_EROSION
  ],
  [PROJECT_PAYLOAD_LEVELS.MAIN_RISK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.MAIN_RISK
  ],
  [PROJECT_PAYLOAD_LEVELS.PROPERTY_AFFECTED_FLOODING]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NO_PROPERTIES_AT_RISK,
    PROJECT_PAYLOAD_FIELDS.MAINTAINING_EXISTING_ASSETS,
    PROJECT_PAYLOAD_FIELDS.REDUCING_FLOOD_RISK_50_PLUS,
    PROJECT_PAYLOAD_FIELDS.REDUCING_FLOOD_RISK_LESS_50,
    PROJECT_PAYLOAD_FIELDS.INCREASING_FLOOD_RESILIENCE
  ],
  [PROJECT_PAYLOAD_LEVELS.PROPERTY_AFFECTED_COASTAL_EROSION]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.NO_PROPERTIES_AT_COASTAL_EROSION_RISK,
    PROJECT_PAYLOAD_FIELDS.PROPERTIES_BENEFIT_MAINTAINING_ASSETS_COASTAL,
    PROJECT_PAYLOAD_FIELDS.PROPERTIES_BENEFIT_INVESTMENT_COASTAL_EROSION
  ],
  [PROJECT_PAYLOAD_LEVELS.TWENTY_PERCENT_DEPRIVED]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.PERCENT_PROPERTIES_20_PERCENT_DEPRIVED
  ],
  [PROJECT_PAYLOAD_LEVELS.FORTY_PERCENT_DEPRIVED]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.PERCENT_PROPERTIES_40_PERCENT_DEPRIVED
  ],
  [PROJECT_PAYLOAD_LEVELS.CURRENT_FLOOD_FLUVIAL_RISK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CURRENT_FLOOD_FLUVIAL_RISK
  ],
  [PROJECT_PAYLOAD_LEVELS.CURRENT_FLOOD_SURFACE_WATER_RISK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CURRENT_FLOOD_SURFACE_WATER_RISK
  ],
  [PROJECT_PAYLOAD_LEVELS.CURRENT_COASTAL_EROSION_RISK]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CURRENT_COASTAL_EROSION_RISK
  ],
  [PROJECT_PAYLOAD_LEVELS.APPROACH]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.APPROACH
  ],
  [PROJECT_PAYLOAD_LEVELS.URGENCY_REASON]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.URGENCY_REASON
  ],
  [PROJECT_PAYLOAD_LEVELS.URGENCY_DETAILS]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.URGENCY_REASON,
    PROJECT_PAYLOAD_FIELDS.URGENCY_DETAILS
  ],
  [PROJECT_PAYLOAD_LEVELS.CONFIDENCE_HOMES_BETTER_PROTECTED]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CONFIDENCE_HOMES_BETTER_PROTECTED
  ],
  [PROJECT_PAYLOAD_LEVELS.CONFIDENCE_HOMES_BY_GATEWAY_FOUR]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CONFIDENCE_HOMES_BY_GATEWAY_FOUR
  ],
  [PROJECT_PAYLOAD_LEVELS.CONFIDENCE_SECURED_PARTNERSHIP_FUNDING]: [
    PROJECT_PAYLOAD_FIELDS.REFERENCE_NUMBER,
    PROJECT_PAYLOAD_FIELDS.CONFIDENCE_SECURED_PARTNERSHIP_FUNDING
  ]
}
