export const PROJECT_STEPS = {
  START: 'start',
  NAME: 'name',
  AREA: 'area',
  TYPE: 'type',
  INTERVENTION_TYPE: 'intervention-types',
  PRIMARY_INTERVENTION_TYPE: 'primary-intervention-type',
  FINANCIAL_START_YEAR: 'financial-start-year',
  FINANCIAL_START_YEAR_MANUAL: 'financial-start-year-manual',
  FINANCIAL_END_YEAR: 'financial-end-year',
  FINANCIAL_END_YEAR_MANUAL: 'financial-end-year-manual',
  START_OUTLINE_BUSINESS_CASE: 'start-outline-business-case',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'complete-outline-business-case',
  AWARD_MAIN_CONTRACT: 'award-main-contract',
  START_WORK: 'start-work',
  START_BENEFITS: 'start-benefits',
  COULD_START_EARLY: 'could-start-early',
  EARLIEST_START_DATE: 'earliest-start-date',
  BENEFIT_AREA: 'benefit-area'
}

export const PROJECT_SESSION_KEY = 'projectData'

export const PROJECT_PAYLOAD_FIELDS = {
  ID: 'id',
  SLUG: 'slug',
  REFERENCE_NUMBER: 'referenceNumber',
  NAME: 'name',
  AREA_ID: 'areaId',
  PROJECT_TYPE: 'projectType',
  PROJECT_INTERVENTION_TYPES: 'projectInterventionTypes',
  MAIN_INTERVENTION_TYPE: 'mainInterventionType',
  FINANCIAL_START_YEAR: 'financialStartYear',
  FINANCIAL_END_YEAR: 'financialEndYear',
  PROJECT_STATE: 'projectState',
  UPDATED_AT: 'updatedAt',
  START_OUTLINE_BUSINESS_CASE_MONTH: 'startOutlineBusinessCaseMonth',
  START_OUTLINE_BUSINESS_CASE_YEAR: 'startOutlineBusinessCaseYear',
  COMPLETE_OUTLINE_BUSINESS_CASE_MONTH: 'completeOutlineBusinessCaseMonth',
  COMPLETE_OUTLINE_BUSINESS_CASE_YEAR: 'completeOutlineBusinessCaseYear',
  AWARD_CONTRACT_MONTH: 'awardContractMonth',
  AWARD_CONTRACT_YEAR: 'awardContractYear',
  START_CONSTRUCTION_MONTH: 'startConstructionMonth',
  START_CONSTRUCTION_YEAR: 'startConstructionYear',
  READY_FOR_SERVICE_MONTH: 'readyForServiceMonth',
  READY_FOR_SERVICE_YEAR: 'readyForServiceYear',
  COULD_START_EARLY: 'couldStartEarly',
  EARLIEST_WITH_GIA_MONTH: 'earliestWithGiaMonth',
  EARLIEST_WITH_GIA_YEAR: 'earliestWithGiaYear'
}

export const PROJECT_PAYLOAD_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_MAIN_CONTRACT: 'AWARD_CONTRACT',
  START_WORK: 'START_CONSTRUCTION',
  START_BENEFITS: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_START_DATE: 'EARLIEST_WITH_GIA'
}

export const PROJECT_TYPES = {
  DEF: 'DEF',
  REP: 'REP',
  REF: 'REF',
  HCR: 'HCR',
  STR: 'STR',
  STU: 'STU',
  ELO: 'ELO'
}

export const PROJECT_INTERVENTION_TYPES = {
  NFM: 'NFM',
  SUDS: 'SUDS',
  PFR: 'PFR',
  OTHER: 'Other'
}

export const PROJECT_VALIDATION_MESSAGES = {
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_IN_PAST: 'DATE_IN_PAST',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_END: 'DATE_AFTER_FINANCIAL_END',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID'
}

export const PROJECT_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR'
}

export const PROJECT_VIEW_ERROR_CODES = {
  ...PROJECT_VALIDATION_MESSAGES,
  ...PROJECT_ERROR_CODES
}

export const PROJECT_STATUS = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  COMPLETED: 'completed',
  ARCHIVED: 'archived'
}
