export const PROJECT_STEPS = {
  START: 'start',
  NAME: 'name',
  AREA: 'area',
  TYPE: 'type',
  INTERVENTION_TYPE: 'intervention-types',
  PRIMARY_INTERVENTION_TYPE: 'primary-intervention-type',
  FINANCIAL_START_YEAR: 'financial-start-year',
  FINANCIAL_START_YEAR_MANUAL: 'financial-start-year-manual',
  FINANCIAL_END_YEAR: 'financial-end-year',
  FINANCIAL_END_YEAR_MANUAL: 'financial-end-year-manual',
  START_OUTLINE_BUSINESS_CASE: 'start-outline-business-case',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'complete-outline-business-case',
  AWARD_MAIN_CONTRACT: 'award-main-contract',
  START_WORK: 'start-work',
  START_BENEFITS: 'start-benefits',
  COULD_START_EARLY: 'could-start-early',
  EARLIEST_START_DATE: 'earliest-start-date',
  BENEFIT_AREA: 'benefit-area',
  RISK: 'risk',
  MAIN_RISK: 'main-risk',
  PROPERTY_AFFECTED_FLOODING: 'property-affected-flooding',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'property-affected-coastal-erosion',
  TWENTY_PERCENT_DEPRIVED: 'twenty-percent-deprived',
  FORTY_PERCENT_DEPRIVED: 'forty-percent-deprived',
  CURRENT_FLOOD_FLUVIAL_RISK: 'current-flood-fluvial-risk',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'current-flood-surface-water-risk',
  CURRENT_COASTAL_EROSION_RISK: 'current-coastal-erosion-risk'
}

export const REFERENCE_NUMBER_PARAM = '{referenceNumber}'

export const PROJECT_SESSION_KEY = 'projectData'

export const PROJECT_PAYLOAD_FIELDS = {
  ID: 'id',
  SLUG: 'slug',
  REFERENCE_NUMBER: 'referenceNumber',
  NAME: 'name',
  AREA_ID: 'areaId',
  PROJECT_TYPE: 'projectType',
  PROJECT_INTERVENTION_TYPES: 'projectInterventionTypes',
  MAIN_INTERVENTION_TYPE: 'mainInterventionType',
  FINANCIAL_START_YEAR: 'financialStartYear',
  FINANCIAL_END_YEAR: 'financialEndYear',
  PROJECT_STATE: 'projectState',
  UPDATED_AT: 'updatedAt',
  START_OUTLINE_BUSINESS_CASE_MONTH: 'startOutlineBusinessCaseMonth',
  START_OUTLINE_BUSINESS_CASE_YEAR: 'startOutlineBusinessCaseYear',
  COMPLETE_OUTLINE_BUSINESS_CASE_MONTH: 'completeOutlineBusinessCaseMonth',
  COMPLETE_OUTLINE_BUSINESS_CASE_YEAR: 'completeOutlineBusinessCaseYear',
  AWARD_CONTRACT_MONTH: 'awardContractMonth',
  AWARD_CONTRACT_YEAR: 'awardContractYear',
  START_CONSTRUCTION_MONTH: 'startConstructionMonth',
  START_CONSTRUCTION_YEAR: 'startConstructionYear',
  READY_FOR_SERVICE_MONTH: 'readyForServiceMonth',
  READY_FOR_SERVICE_YEAR: 'readyForServiceYear',
  COULD_START_EARLY: 'couldStartEarly',
  EARLIEST_WITH_GIA_MONTH: 'earliestWithGiaMonth',
  EARLIEST_WITH_GIA_YEAR: 'earliestWithGiaYear',
  BENEFIT_AREA_FILE_NAME: 'benefitAreaFileName',
  BENEFIT_AREA_FILE_SIZE: 'benefitAreaFileSize',
  BENEFIT_AREA_CONTENT_TYPE: 'benefitAreaContentType',
  BENEFIT_AREA_FILE_S3_BUCKET: 'benefitAreaFileS3Bucket',
  BENEFIT_AREA_FILE_S3_KEY: 'benefitAreaFileS3Key',
  BENEFIT_AREA_FILE_UPDATED_AT: 'benefitAreaFileUpdatedAt',
  BENEFIT_AREA_FILE_DOWNLOAD_URL: 'benefitAreaFileDownloadUrl',
  BENEFIT_AREA_FILE_DOWNLOAD_EXPIRY: 'benefitAreaFileDownloadExpiry',
  RISKS: 'risks',
  MAIN_RISK: 'mainRisk',
  NO_PROPERTIES_AT_RISK: 'noPropertiesAtRisk',
  MAINTAINING_EXISTING_ASSETS: 'maintainingExistingAssets',
  REDUCING_FLOOD_RISK_50_PLUS: 'reducingFloodRisk50Plus',
  REDUCING_FLOOD_RISK_LESS_50: 'reducingFloodRiskLess50',
  INCREASING_FLOOD_RESILIENCE: 'increasingFloodResilience',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK: 'noPropertiesAtCoastalErosionRisk',
  PROPERTIES_BENEFIT_MAINTAINING_ASSETS_COASTAL:
    'propertiesBenefitMaintainingAssetsCoastal',
  PROPERTIES_BENEFIT_INVESTMENT_COASTAL_EROSION:
    'propertiesBenefitInvestmentCoastalErosion',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED: 'percentProperties20PercentDeprived',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED: 'percentProperties40PercentDeprived',
  CURRENT_FLOOD_FLUVIAL_RISK: 'currentFloodFluvialRisk',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'currentFloodSurfaceWaterRisk',
  CURRENT_COASTAL_EROSION_RISK: 'currentCoastalErosionRisk'
}

export const PROJECT_PAYLOAD_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_MAIN_CONTRACT: 'AWARD_CONTRACT',
  START_WORK: 'START_CONSTRUCTION',
  START_BENEFITS: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_START_DATE: 'EARLIEST_WITH_GIA',
  RISK: 'RISK',
  MAIN_RISK: 'MAIN_RISK',
  PROPERTY_AFFECTED_FLOODING: 'PROPERTY_AFFECTED_FLOODING',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'PROPERTY_AFFECTED_COASTAL_EROSION',
  TWENTY_PERCENT_DEPRIVED: 'TWENTY_PERCENT_DEPRIVED',
  FORTY_PERCENT_DEPRIVED: 'FORTY_PERCENT_DEPRIVED',
  CURRENT_FLOOD_FLUVIAL_RISK: 'CURRENT_FLOOD_FLUVIAL_RISK',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'CURRENT_FLOOD_SURFACE_WATER_RISK',
  CURRENT_COASTAL_EROSION_RISK: 'CURRENT_COASTAL_EROSION_RISK'
}

export const PROJECT_TYPES = {
  DEF: 'DEF',
  REP: 'REP',
  REF: 'REF',
  HCR: 'HCR',
  STR: 'STR',
  STU: 'STU',
  ELO: 'ELO'
}

export const PROJECT_INTERVENTION_TYPES = {
  NFM: 'NFM',
  SUDS: 'SUDS',
  PFR: 'PFR',
  OTHER: 'Other'
}

export const PROJECT_RISK_TYPES = {
  FLUVIAL: 'fluvial_flooding',
  TIDAL: 'tidal_flooding',
  GROUNDWATER: 'groundwater_flooding',
  SURFACE_WATER: 'surface_water_flooding',
  SEA: 'sea_flooding',
  RESERVOIR: 'reservoir_flooding',
  COASTAL_EROSION: 'coastal_erosion'
}

export const FLOOD_RISK_LEVELS = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  VERY_LOW: 'very_low'
}

export const COASTAL_EROSION_RISK_LEVELS = {
  MEDIUM_TERM: 'medium_term',
  LONGER_TERM: 'longer_term'
}

export const PROJECT_VALIDATION_MESSAGES = {
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_IN_PAST: 'DATE_IN_PAST',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_END: 'DATE_AFTER_FINANCIAL_END',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID',
  FAILED_TO_UPLOAD_FILE: 'FAILED_TO_UPLOAD_FILE',
  RISKS_REQUIRED: 'RISKS_REQUIRED',
  RISKS_INVALID: 'RISKS_INVALID',
  MAIN_RISK_REQUIRED: 'MAIN_RISK_REQUIRED',
  MAIN_RISK_INVALID: 'MAIN_RISK_INVALID',
  PROPERTY_VALUE_INVALID: 'PROPERTY_VALUE_INVALID'
}

/**
 * Upload status values
 * Represents the current state of the file upload process
 */
export const UPLOAD_STATUS = {
  PENDING: 'pending', // Upload initiated but not started
  PROCESSING: 'processing', // Files being downloaded/processed by CDP
  INITIATED: 'initiated', // Upload session created
  READY: 'ready', // Upload complete and file available
  FAILED: 'failed' // Upload failed
}

export const PROJECT_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR'
}

export const PROJECT_VIEW_ERROR_CODES = {
  ...PROJECT_VALIDATION_MESSAGES,
  ...PROJECT_ERROR_CODES
}

export const PROJECT_STATUS = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  COMPLETED: 'completed',
  ARCHIVED: 'archived'
}
