export const PROJECT_STEPS = {
  START: 'start',
  NAME: 'name',
  AREA: 'area',
  TYPE: 'type',
  INTERVENTION_TYPE: 'intervention-types',
  PRIMARY_INTERVENTION_TYPE: 'primary-intervention-type',
  FINANCIAL_START_YEAR: 'financial-start-year',
  FINANCIAL_START_YEAR_MANUAL: 'financial-start-year-manual',
  FINANCIAL_END_YEAR: 'financial-end-year',
  FINANCIAL_END_YEAR_MANUAL: 'financial-end-year-manual',
  START_OUTLINE_BUSINESS_CASE: 'start-outline-business-case',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'complete-outline-business-case',
  AWARD_MAIN_CONTRACT: 'award-main-contract',
  START_WORK: 'start-work',
  START_BENEFITS: 'start-benefits',
  COULD_START_EARLY: 'could-start-early',
  EARLIEST_START_DATE: 'earliest-start-date',
  BENEFIT_AREA: 'benefit-area',
  RISK: 'risk',
  MAIN_RISK: 'main-risk',
  PROPERTY_AFFECTED_FLOODING: 'property-affected-flooding',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'property-affected-coastal-erosion',
  TWENTY_PERCENT_DEPRIVED: 'twenty-percent-deprived',
  FORTY_PERCENT_DEPRIVED: 'forty-percent-deprived',
  CURRENT_FLOOD_FLUVIAL_RISK: 'current-flood-fluvial-risk',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'current-flood-surface-water-risk',
  CURRENT_COASTAL_EROSION_RISK: 'current-coastal-erosion-risk',
  PROJECT_GOALS: 'project-goals',
  URGENCY_REASON: 'urgency-reason',
  URGENCY_DETAILS: 'urgency-details',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'confidence-homes-better-protected',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'confidence-homes-by-gateway-four',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING:
    'confidence-secured-partnership-funding',
  ENVIRONMENTAL_BENEFITS: 'environmental-benefits',
  INTERTIDAL_HABITAT: 'intertidal-habitat',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-intertidal-habitat-created-or-enhanced',
  WOODLAND: 'woodland',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-woodland-habitat-created-or-enhanced',
  WET_WOODLAND: 'wet-woodland',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-wet-woodland-habitat-created-or-enhanced',
  WETLAND_OR_WET_GRASSLAND: 'wetland-or-wet-grassland',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'hectares-of-wetland-or-wet-grassland-created-or-enhanced',
  GRASSLAND: 'grassland',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-grassland-habitat-created-or-enhanced',
  HEATHLAND: 'heathland',
  HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED:
    'hectares-of-heathland-created-or-enhanced',
  PONDS_LAKES: 'ponds-lakes',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-pond-or-lake-habitat-created-or-enhanced',
  ARABLE_LAND: 'arable-land',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectares-of-arable-land-lake-habitat-created-or-enhanced',
  COMPREHENSIVE_RESTORATION: 'comprehensive-restoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'kilometres-of-watercourse-enhanced-or-created-comprehensive',
  PARTIAL_RESTORATION: 'partial-restoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'kilometres-of-watercourse-enhanced-or-created-partial',
  CREATE_HABITAT_WATERCOURSE: 'create-habitat-watercourse',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'kilometres-of-watercourse-enhanced-or-created-single'
}

export const REFERENCE_NUMBER_PARAM = '{referenceNumber}'

export const PROJECT_SESSION_KEY = 'projectData'

export const PROJECT_PAYLOAD_FIELDS = {
  ID: 'id',
  SLUG: 'slug',
  REFERENCE_NUMBER: 'referenceNumber',
  NAME: 'name',
  AREA_ID: 'areaId',
  PROJECT_TYPE: 'projectType',
  PROJECT_INTERVENTION_TYPES: 'projectInterventionTypes',
  MAIN_INTERVENTION_TYPE: 'mainInterventionType',
  FINANCIAL_START_YEAR: 'financialStartYear',
  FINANCIAL_END_YEAR: 'financialEndYear',
  PROJECT_STATE: 'projectState',
  UPDATED_AT: 'updatedAt',
  START_OUTLINE_BUSINESS_CASE_MONTH: 'startOutlineBusinessCaseMonth',
  START_OUTLINE_BUSINESS_CASE_YEAR: 'startOutlineBusinessCaseYear',
  COMPLETE_OUTLINE_BUSINESS_CASE_MONTH: 'completeOutlineBusinessCaseMonth',
  COMPLETE_OUTLINE_BUSINESS_CASE_YEAR: 'completeOutlineBusinessCaseYear',
  AWARD_CONTRACT_MONTH: 'awardContractMonth',
  AWARD_CONTRACT_YEAR: 'awardContractYear',
  START_CONSTRUCTION_MONTH: 'startConstructionMonth',
  START_CONSTRUCTION_YEAR: 'startConstructionYear',
  READY_FOR_SERVICE_MONTH: 'readyForServiceMonth',
  READY_FOR_SERVICE_YEAR: 'readyForServiceYear',
  COULD_START_EARLY: 'couldStartEarly',
  EARLIEST_WITH_GIA_MONTH: 'earliestWithGiaMonth',
  EARLIEST_WITH_GIA_YEAR: 'earliestWithGiaYear',
  BENEFIT_AREA_FILE_NAME: 'benefitAreaFileName',
  BENEFIT_AREA_FILE_SIZE: 'benefitAreaFileSize',
  BENEFIT_AREA_CONTENT_TYPE: 'benefitAreaContentType',
  BENEFIT_AREA_FILE_S3_BUCKET: 'benefitAreaFileS3Bucket',
  BENEFIT_AREA_FILE_S3_KEY: 'benefitAreaFileS3Key',
  BENEFIT_AREA_FILE_UPDATED_AT: 'benefitAreaFileUpdatedAt',
  BENEFIT_AREA_FILE_DOWNLOAD_URL: 'benefitAreaFileDownloadUrl',
  BENEFIT_AREA_FILE_DOWNLOAD_EXPIRY: 'benefitAreaFileDownloadExpiry',
  RISKS: 'risks',
  MAIN_RISK: 'mainRisk',
  NO_PROPERTIES_AT_RISK: 'noPropertiesAtRisk',
  MAINTAINING_EXISTING_ASSETS: 'maintainingExistingAssets',
  REDUCING_FLOOD_RISK_50_PLUS: 'reducingFloodRisk50Plus',
  REDUCING_FLOOD_RISK_LESS_50: 'reducingFloodRiskLess50',
  INCREASING_FLOOD_RESILIENCE: 'increasingFloodResilience',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK: 'noPropertiesAtCoastalErosionRisk',
  PROPERTIES_BENEFIT_MAINTAINING_ASSETS_COASTAL:
    'propertiesBenefitMaintainingAssetsCoastal',
  PROPERTIES_BENEFIT_INVESTMENT_COASTAL_EROSION:
    'propertiesBenefitInvestmentCoastalErosion',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED: 'percentProperties20PercentDeprived',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED: 'percentProperties40PercentDeprived',
  CURRENT_FLOOD_FLUVIAL_RISK: 'currentFloodFluvialRisk',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'currentFloodSurfaceWaterRisk',
  CURRENT_COASTAL_EROSION_RISK: 'currentCoastalErosionRisk',
  APPROACH: 'approach',
  URGENCY_REASON: 'urgencyReason',
  URGENCY_DETAILS: 'urgencyDetails',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'confidenceHomesBetterProtected',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'confidenceHomesByGatewayFour',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING: 'confidenceSecuredPartnershipFunding',
  ENVIRONMENTAL_BENEFITS: 'environmentalBenefits',
  INTERTIDAL_HABITAT: 'intertidalHabitat',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfIntertidalHabitatCreatedOrEnhanced',
  WOODLAND: 'woodland',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfWoodlandHabitatCreatedOrEnhanced',
  WET_WOODLAND: 'wetWoodland',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfWetWoodlandHabitatCreatedOrEnhanced',
  WETLAND_OR_WET_GRASSLAND: 'wetlandOrWetGrassland',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'hectaresOfWetlandOrWetGrasslandCreatedOrEnhanced',
  GRASSLAND: 'grassland',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfGrasslandHabitatCreatedOrEnhanced',
  HEATHLAND: 'heathland',
  HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED:
    'hectaresOfHeathlandCreatedOrEnhanced',
  PONDS_LAKES: 'pondsLakes',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfPondOrLakeHabitatCreatedOrEnhanced',
  ARABLE_LAND: 'arableLand',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfArableLandLakeHabitatCreatedOrEnhanced',
  COMPREHENSIVE_RESTORATION: 'comprehensiveRestoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'kilometresOfWatercourseEnhancedOrCreatedComprehensive',
  PARTIAL_RESTORATION: 'partialRestoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'kilometresOfWatercourseEnhancedOrCreatedPartial',
  CREATE_HABITAT_WATERCOURSE: 'createHabitatWatercourse',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'kilometresOfWatercourseEnhancedOrCreatedSingle'
}

export const PROJECT_PAYLOAD_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_MAIN_CONTRACT: 'AWARD_CONTRACT',
  START_WORK: 'START_CONSTRUCTION',
  START_BENEFITS: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_START_DATE: 'EARLIEST_WITH_GIA',
  RISK: 'RISK',
  MAIN_RISK: 'MAIN_RISK',
  PROPERTY_AFFECTED_FLOODING: 'PROPERTY_AFFECTED_FLOODING',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'PROPERTY_AFFECTED_COASTAL_EROSION',
  TWENTY_PERCENT_DEPRIVED: 'TWENTY_PERCENT_DEPRIVED',
  FORTY_PERCENT_DEPRIVED: 'FORTY_PERCENT_DEPRIVED',
  CURRENT_FLOOD_FLUVIAL_RISK: 'CURRENT_FLOOD_FLUVIAL_RISK',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'CURRENT_FLOOD_SURFACE_WATER_RISK',
  CURRENT_COASTAL_EROSION_RISK: 'CURRENT_COASTAL_EROSION_RISK',
  APPROACH: 'APPROACH',
  URGENCY_REASON: 'URGENCY_REASON',
  URGENCY_DETAILS: 'URGENCY_DETAILS',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'CONFIDENCE_HOMES_BETTER_PROTECTED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'CONFIDENCE_HOMES_BY_GATEWAY_FOUR',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING',
  ENVIRONMENTAL_BENEFITS: 'ENVIRONMENTAL_BENEFITS',
  INTERTIDAL_HABITAT: 'INTERTIDAL_HABITAT',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED',
  WOODLAND: 'WOODLAND',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WET_WOODLAND: 'WET_WOODLAND',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WETLAND_OR_WET_GRASSLAND: 'WETLAND_OR_WET_GRASSLAND',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED',
  GRASSLAND: 'GRASSLAND',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED',
  HEATHLAND: 'HEATHLAND',
  HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED:
    'HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED',
  PONDS_LAKES: 'PONDS_LAKES',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED',
  ARABLE_LAND: 'ARABLE_LAND',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED',
  COMPREHENSIVE_RESTORATION: 'COMPREHENSIVE_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE',
  PARTIAL_RESTORATION: 'PARTIAL_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL',
  CREATE_HABITAT_WATERCOURSE: 'CREATE_HABITAT_WATERCOURSE',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE'
}

export const PROJECT_TYPES = {
  DEF: 'DEF',
  REP: 'REP',
  REF: 'REF',
  HCR: 'HCR',
  STR: 'STR',
  STU: 'STU',
  ELO: 'ELO'
}

export const PROJECT_INTERVENTION_TYPES = {
  NFM: 'NFM',
  SUDS: 'SUDS',
  PFR: 'PFR',
  OTHER: 'Other'
}

export const PROJECT_RISK_TYPES = {
  FLUVIAL: 'fluvial_flooding',
  TIDAL: 'tidal_flooding',
  GROUNDWATER: 'groundwater_flooding',
  SURFACE_WATER: 'surface_water_flooding',
  SEA: 'sea_flooding',
  RESERVOIR: 'reservoir_flooding',
  COASTAL_EROSION: 'coastal_erosion'
}

export const FLOOD_RISK_LEVELS = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  VERY_LOW: 'very_low'
}

export const COASTAL_EROSION_RISK_LEVELS = {
  MEDIUM_TERM: 'medium_term',
  LONGER_TERM: 'longer_term'
}

export const PROJECT_VALIDATION_MESSAGES = {
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_OUT_OF_RANGE: 'FINANCIAL_START_YEAR_OUT_OF_RANGE',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_OUT_OF_RANGE: 'FINANCIAL_END_YEAR_OUT_OF_RANGE',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_OUTSIDE_FINANCIAL_RANGE: 'DATE_OUTSIDE_FINANCIAL_RANGE',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_OBC_START: 'DATE_AFTER_OBC_START',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID',
  FAILED_TO_UPLOAD_FILE: 'FAILED_TO_UPLOAD_FILE',
  RISKS_REQUIRED: 'RISKS_REQUIRED',
  RISKS_INVALID: 'RISKS_INVALID',
  MAIN_RISK_REQUIRED: 'MAIN_RISK_REQUIRED',
  MAIN_RISK_INVALID: 'MAIN_RISK_INVALID',
  PROPERTY_VALUE_INVALID: 'PROPERTY_VALUE_INVALID',
  APPROACH_REQUIRED: 'APPROACH_REQUIRED',
  APPROACH_MAX_LENGTH: 'APPROACH_MAX_LENGTH',
  URGENCY_REASON_REQUIRED: 'URGENCY_REASON_REQUIRED',
  URGENCY_REASON_INVALID: 'URGENCY_REASON_INVALID',
  URGENCY_DETAILS_REQUIRED: 'URGENCY_DETAILS_REQUIRED',
  URGENCY_DETAILS_MAX_LENGTH: 'URGENCY_DETAILS_MAX_LENGTH',
  CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED',
  CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID',
  ENVIRONMENTAL_BENEFITS_REQUIRED: 'ENVIRONMENTAL_BENEFITS_REQUIRED',
  ENVIRONMENTAL_BENEFITS_INVALID: 'ENVIRONMENTAL_BENEFITS_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED',
  ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_MIN: 'ENVIRONMENTAL_BENEFITS_QUANTITY_MIN',
  ENVIRONMENTAL_BENEFITS_QUANTITY_PRECISION:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_PRECISION'
}

/**
 * Upload status values
 * Represents the current state of the file upload process
 */
export const UPLOAD_STATUS = {
  PENDING: 'pending', // Upload initiated but not started
  PROCESSING: 'processing', // Files being downloaded/processed by CDP
  INITIATED: 'initiated', // Upload session created
  READY: 'ready', // Upload complete and file available
  FAILED: 'failed' // Upload failed
}

export const PROJECT_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR'
}

export const PROJECT_VIEW_ERROR_CODES = {
  ...PROJECT_VALIDATION_MESSAGES,
  ...PROJECT_ERROR_CODES
}

export const URGENCY_REASONS = {
  NOT_URGENT: 'not_urgent',
  STATUTORY_NEED: 'statutory_need',
  LEGAL_NEED: 'legal_need',
  HEALTH_AND_SAFETY: 'health_and_safety',
  EMERGENCY_WORKS: 'emergency_works',
  TIME_LIMITED: 'time_limited'
}

export const CONFIDENCE_LEVELS = {
  HIGH: 'high',
  MEDIUM_HIGH: 'medium_high',
  MEDIUM_LOW: 'medium_low',
  LOW: 'low',
  NOT_APPLICABLE: 'not_applicable'
}

export const PROJECT_STATUS = {
  REVISE: 'revise',
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  COMPLETED: 'completed',
  ARCHIVED: 'archived'
}

export const EDITABLE_STATUSES = [PROJECT_STATUS.DRAFT, PROJECT_STATUS.REVISE]
