/**
 * Validation codes - used for client-side validation error messages
 * These match the backend AUTH_VALIDATION_CODES for consistency
 */
export const VALIDATION_CODES = {
  // Email validation
  EMAIL_REQUIRED: 'VALIDATION_EMAIL_REQUIRED',
  EMAIL_INVALID_FORMAT: 'VALIDATION_EMAIL_INVALID_FORMAT',
  EMAIL_TOO_LONG: 'VALIDATION_EMAIL_TOO_LONG',

  // Password validation
  PASSWORD_REQUIRED: 'VALIDATION_PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'VALIDATION_PASSWORD_MIN_LENGTH',
  PASSWORD_MAX_LENGTH: 'VALIDATION_PASSWORD_MAX_LENGTH',
  PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',
  PASSWORD_STRENGTH_UPPERCASE: 'PASSWORD_STRENGTH_UPPERCASE',
  PASSWORD_STRENGTH_LOWERCASE: 'PASSWORD_STRENGTH_LOWERCASE',
  PASSWORD_STRENGTH_NUMBER: 'PASSWORD_STRENGTH_NUMBER',
  PASSWORD_STRENGTH_SPECIAL: 'PASSWORD_STRENGTH_SPECIAL',

  // Token validation
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  TOKEN_TYPE_REQUIRED: 'VALIDATION_TOKEN_TYPE_REQUIRED',
  TOKEN_TYPE_INVALID: 'VALIDATION_TOKEN_TYPE_INVALID',

  // Account field validation
  FIRST_NAME_REQUIRED: 'VALIDATION_FIRST_NAME_REQUIRED',
  FIRST_NAME_TOO_LONG: 'VALIDATION_FIRST_NAME_TOO_LONG',
  LAST_NAME_REQUIRED: 'VALIDATION_LAST_NAME_REQUIRED',
  LAST_NAME_TOO_LONG: 'VALIDATION_LAST_NAME_TOO_LONG',
  JOB_TITLE_REQUIRED: 'VALIDATION_JOB_TITLE_REQUIRED',
  JOB_TITLE_TOO_LONG: 'VALIDATION_JOB_TITLE_TOO_LONG',
  ORGANISATION_REQUIRED: 'VALIDATION_ORGANISATION_REQUIRED',
  ORGANISATION_TOO_LONG: 'VALIDATION_ORGANISATION_TOO_LONG',
  TELEPHONE_REQUIRED: 'VALIDATION_TELEPHONE_REQUIRED',
  TELEPHONE_INVALID_FORMAT: 'VALIDATION_TELEPHONE_INVALID_FORMAT',
  TELEPHONE_TOO_LONG: 'VALIDATION_TELEPHONE_TOO_LONG',
  RESPONSIBILITY_REQUIRED: 'VALIDATION_RESPONSIBILITY_REQUIRED',
  RESPONSIBILITY_INVALID: 'VALIDATION_RESPONSIBILITY_INVALID',
  ADMIN_FLAG_INVALID: 'VALIDATION_ADMIN_FLAG_INVALID',
  ADMIN_FLAG_REQUIRED: 'VALIDATION_ADMIN_FLAG_REQUIRED',
  USER_ID_INVALID: 'VALIDATION_USER_ID_INVALID',

  // Area validation
  AREA_ID_INVALID: 'VALIDATION_AREA_ID_INVALID',
  AREA_ID_REQUIRED: 'VALIDATION_AREA_ID_REQUIRED',
  PRIMARY_FLAG_INVALID: 'VALIDATION_PRIMARY_FLAG_INVALID',
  AREAS_REQUIRED: 'VALIDATION_AREAS_REQUIRED',
  MAIN_AREA_REQUIRED: 'VALIDATION_MAIN_AREA_REQUIRED',

  // Email validation (backend errors)
  EMAIL_DISPOSABLE: 'VALIDATION_EMAIL_DISPOSABLE',
  EMAIL_DOMAIN_INVALID: 'VALIDATION_EMAIL_DOMAIN_INVALID',
  EMAIL_DUPLICATE: 'VALIDATION_EMAIL_DUPLICATE',
  EMAIL_LOCAL_TOO_LONG: 'VALIDATION_EMAIL_LOCAL_TOO_LONG',

  // Name validation
  FIRST_NAME_INVALID_FORMAT: 'VALIDATION_FIRST_NAME_INVALID_FORMAT',
  LAST_NAME_INVALID_FORMAT: 'VALIDATION_LAST_NAME_INVALID_FORMAT',
  JOB_TITLE_INVALID_FORMAT: 'VALIDATION_JOB_TITLE_INVALID_FORMAT',
  ORGANISATION_INVALID_FORMAT: 'VALIDATION_ORGANISATION_INVALID_FORMAT'
}

/**
 * Auth error codes - returned from backend API
 */
export const AUTH_ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  ACCOUNT_SETUP_INCOMPLETE: 'AUTH_ACCOUNT_SETUP_INCOMPLETE',

  // Warning codes
  LAST_ATTEMPT_WARNING: 'AUTH_LAST_ATTEMPT_WARNING',

  // Support codes
  SUPPORT_UNLOCK_ACCOUNT: 'AUTH_SUPPORT_UNLOCK_ACCOUNT',
  SUPPORT_CONTACT: 'AUTH_SUPPORT_CONTACT',

  // Token errors
  TOKEN_EXPIRED_OR_INVALID: 'AUTH_TOKEN_EXPIRED_OR_INVALID',
  RESET_TOKEN_EXPIRED_OR_INVALID: 'AUTH_RESET_TOKEN_EXPIRED_INVALID',
  INVITATION_TOKEN_EXPIRED_OR_INVALID: 'AUTH_INVITATION_TOKEN_EXPIRED_INVALID',

  // Password errors
  PASSWORD_WAS_USED_PREVIOUSLY: 'AUTH_PASSWORD_WAS_USED_PREVIOUSLY',

  // Session errors
  SESSION_MISMATCH: 'AUTH_SESSION_MISMATCH',
  SESSION_ALREADY_INVALIDATED: 'AUTH_SESSION_ALREADY_INVALIDATED',
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',

  // Network/system errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}

export const VIEW_ERROR_CODES = {
  ...AUTH_ERROR_CODES,
  ...VALIDATION_CODES
}
