/**
 * SIZE
 */
export const SIZE = {
  LENGTH_8: 8,
  LENGTH_32: 32,
  LENGTH_128: 128,
  LENGTH_254: 254
}

/**
 * Validation codes - used for client-side validation error messages
 * These match the backend AUTH_VALIDATION_CODES for consistency
 */
export const VALIDATION_CODES = {
  // Email validation
  EMAIL_REQUIRED: 'VALIDATION_EMAIL_REQUIRED',
  EMAIL_INVALID_FORMAT: 'VALIDATION_EMAIL_INVALID_FORMAT',
  EMAIL_TOO_LONG: 'VALIDATION_EMAIL_TOO_LONG',

  // Password validation
  PASSWORD_REQUIRED: 'VALIDATION_PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'VALIDATION_PASSWORD_MIN_LENGTH',
  PASSWORD_MAX_LENGTH: 'VALIDATION_PASSWORD_MAX_LENGTH',
  PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',
  PASSWORD_STRENGTH_UPPERCASE: 'PASSWORD_STRENGTH_UPPERCASE',
  PASSWORD_STRENGTH_LOWERCASE: 'PASSWORD_STRENGTH_LOWERCASE',
  PASSWORD_STRENGTH_NUMBER: 'PASSWORD_STRENGTH_NUMBER',
  PASSWORD_STRENGTH_SPECIAL: 'PASSWORD_STRENGTH_SPECIAL',

  // Token validation
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  TOKEN_TYPE_REQUIRED: 'VALIDATION_TOKEN_TYPE_REQUIRED',
  TOKEN_TYPE_INVALID: 'VALIDATION_TOKEN_TYPE_INVALID'
}

/**
 * Auth error codes - returned from backend API
 */
export const AUTH_ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  ACCOUNT_SETUP_INCOMPLETE: 'AUTH_ACCOUNT_SETUP_INCOMPLETE',
  CONCURRENT_SESSION: 'AUTH_CONCURRENT_SESSION',

  // Warning codes
  LAST_ATTEMPT_WARNING: 'AUTH_LAST_ATTEMPT_WARNING',

  // Support codes
  SUPPORT_UNLOCK_ACCOUNT: 'AUTH_SUPPORT_UNLOCK_ACCOUNT',
  SUPPORT_CONTACT: 'AUTH_SUPPORT_CONTACT',

  // Token errors
  TOKEN_EXPIRED_OR_INVALID: 'AUTH_TOKEN_EXPIRED_OR_INVALID',
  RESET_TOKEN_EXPIRED_OR_INVALID: 'AUTH_RESET_TOKEN_EXPIRED_INVALID',
  INVITATION_TOKEN_EXPIRED_OR_INVALID: 'AUTH_INVITATION_TOKEN_EXPIRED_INVALID',

  // Password errors
  PASSWORD_WAS_USED_PREVIOUSLY: 'AUTH_PASSWORD_WAS_USED_PREVIOUSLY',

  // Session errors
  SESSION_MISMATCH: 'AUTH_SESSION_MISMATCH',
  SESSION_ALREADY_INVALIDATED: 'AUTH_SESSION_ALREADY_INVALIDATED',
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',

  // Network/system errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}

export const VIEW_ERROR_CODES = {
  ...AUTH_ERROR_CODES,
  ...VALIDATION_CODES
}

/**
 * Token Types
 */
export const TOKEN_TYPES = {
  RESET: 'RESET',
  INVITATION: 'INVITATION'
}

/**
 * Regex Patterns for validation
 */
export const VALIDATION_PATTERNS = {
  PROJECT_NAME: /^[a-zA-Z0-9_-]+$/
}
