export const PROJECT_PAYLOAD_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_MAIN_CONTRACT: 'AWARD_CONTRACT',
  START_WORK: 'START_CONSTRUCTION',
  START_BENEFITS: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_START_DATE: 'EARLIEST_WITH_GIA',
  RISK: 'RISK',
  MAIN_RISK: 'MAIN_RISK',
  PROPERTY_AFFECTED_FLOODING: 'PROPERTY_AFFECTED_FLOODING',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'PROPERTY_AFFECTED_COASTAL_EROSION',
  TWENTY_PERCENT_DEPRIVED: 'TWENTY_PERCENT_DEPRIVED',
  FORTY_PERCENT_DEPRIVED: 'FORTY_PERCENT_DEPRIVED',
  CURRENT_FLOOD_FLUVIAL_RISK: 'CURRENT_FLOOD_FLUVIAL_RISK',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'CURRENT_FLOOD_SURFACE_WATER_RISK',
  CURRENT_COASTAL_EROSION_RISK: 'CURRENT_COASTAL_EROSION_RISK',
  APPROACH: 'APPROACH',
  URGENCY_REASON: 'URGENCY_REASON',
  URGENCY_DETAILS: 'URGENCY_DETAILS',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'CONFIDENCE_HOMES_BETTER_PROTECTED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'CONFIDENCE_HOMES_BY_GATEWAY_FOUR',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING',
  ENVIRONMENTAL_BENEFITS: 'ENVIRONMENTAL_BENEFITS',
  INTERTIDAL_HABITAT: 'INTERTIDAL_HABITAT',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED',
  WOODLAND: 'WOODLAND',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WET_WOODLAND: 'WET_WOODLAND',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WETLAND_OR_WET_GRASSLAND: 'WETLAND_OR_WET_GRASSLAND',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED',
  GRASSLAND: 'GRASSLAND',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED',
  HEATHLAND: 'HEATHLAND',
  HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED:
    'HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED',
  PONDS_LAKES: 'PONDS_LAKES',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED',
  ARABLE_LAND: 'ARABLE_LAND',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED',
  COMPREHENSIVE_RESTORATION: 'COMPREHENSIVE_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE',
  PARTIAL_RESTORATION: 'PARTIAL_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL',
  CREATE_HABITAT_WATERCOURSE: 'CREATE_HABITAT_WATERCOURSE',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE',
  NFM_SELECTED_MEASURES: 'NFM_SELECTED_MEASURES',
  NFM_RIVER_RESTORATION: 'NFM_RIVER_RESTORATION',
  NFM_LEAKY_BARRIERS: 'NFM_LEAKY_BARRIERS',
  NFM_OFFLINE_STORAGE: 'NFM_OFFLINE_STORAGE',
  NFM_WOODLAND: 'NFM_WOODLAND',
  NFM_HEADWATER_DRAINAGE: 'NFM_HEADWATER_DRAINAGE',
  NFM_RUNOFF_MANAGEMENT: 'NFM_RUNOFF_MANAGEMENT',
  NFM_SALTMARSH: 'NFM_SALTMARSH',
  NFM_SAND_DUNE: 'NFM_SAND_DUNE',
  NFM_LAND_USE_CHANGE: 'NFM_LAND_USE_CHANGE',
  NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND:
    'NFM_LAND_USE_ENCLOSED_ARABLE_FARMLAND',
  NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND:
    'NFM_LAND_USE_ENCLOSED_LIVESTOCK_FARMLAND',
  NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND:
    'NFM_LAND_USE_ENCLOSED_DAIRYING_FARMLAND',
  NFM_LAND_USE_SEMI_NATURAL_GRASSLAND: 'NFM_LAND_USE_SEMI_NATURAL_GRASSLAND',
  NFM_LAND_USE_WOODLAND: 'NFM_LAND_USE_WOODLAND',
  NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH:
    'NFM_LAND_USE_MOUNTAIN_MOORS_AND_HEATH',
  NFM_LAND_USE_PEATLAND_RESTORATION: 'NFM_LAND_USE_PEATLAND_RESTORATION',
  NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER:
    'NFM_LAND_USE_RIVERS_WETLANDS_FRESHWATER',
  NFM_LAND_USE_COASTAL_MARGINS: 'NFM_LAND_USE_COASTAL_MARGINS',
  NFM_LANDOWNER_CONSENT: 'NFM_LANDOWNER_CONSENT',
  NFM_EXPERIENCE_LEVEL: 'NFM_EXPERIENCE_LEVEL',
  NFM_PROJECT_READINESS: 'NFM_PROJECT_READINESS',
  WHOLE_LIFE_COST: 'WHOLE_LIFE_COST'
}
