export const PROJECT_PAYLOAD_FIELDS = {
  ID: 'id',
  SLUG: 'slug',
  REFERENCE_NUMBER: 'referenceNumber',
  NAME: 'name',
  AREA_ID: 'areaId',
  PROJECT_TYPE: 'projectType',
  PROJECT_INTERVENTION_TYPES: 'projectInterventionTypes',
  MAIN_INTERVENTION_TYPE: 'mainInterventionType',
  FINANCIAL_START_YEAR: 'financialStartYear',
  FINANCIAL_END_YEAR: 'financialEndYear',
  PROJECT_STATE: 'projectState',
  UPDATED_AT: 'updatedAt',
  START_OUTLINE_BUSINESS_CASE_MONTH: 'startOutlineBusinessCaseMonth',
  START_OUTLINE_BUSINESS_CASE_YEAR: 'startOutlineBusinessCaseYear',
  COMPLETE_OUTLINE_BUSINESS_CASE_MONTH: 'completeOutlineBusinessCaseMonth',
  COMPLETE_OUTLINE_BUSINESS_CASE_YEAR: 'completeOutlineBusinessCaseYear',
  AWARD_CONTRACT_MONTH: 'awardContractMonth',
  AWARD_CONTRACT_YEAR: 'awardContractYear',
  START_CONSTRUCTION_MONTH: 'startConstructionMonth',
  START_CONSTRUCTION_YEAR: 'startConstructionYear',
  READY_FOR_SERVICE_MONTH: 'readyForServiceMonth',
  READY_FOR_SERVICE_YEAR: 'readyForServiceYear',
  COULD_START_EARLY: 'couldStartEarly',
  EARLIEST_WITH_GIA_MONTH: 'earliestWithGiaMonth',
  EARLIEST_WITH_GIA_YEAR: 'earliestWithGiaYear',
  BENEFIT_AREA_FILE_NAME: 'benefitAreaFileName',
  BENEFIT_AREA_FILE_SIZE: 'benefitAreaFileSize',
  BENEFIT_AREA_CONTENT_TYPE: 'benefitAreaContentType',
  BENEFIT_AREA_FILE_S3_BUCKET: 'benefitAreaFileS3Bucket',
  BENEFIT_AREA_FILE_S3_KEY: 'benefitAreaFileS3Key',
  BENEFIT_AREA_FILE_UPDATED_AT: 'benefitAreaFileUpdatedAt',
  BENEFIT_AREA_FILE_DOWNLOAD_URL: 'benefitAreaFileDownloadUrl',
  BENEFIT_AREA_FILE_DOWNLOAD_EXPIRY: 'benefitAreaFileDownloadExpiry',
  RISKS: 'risks',
  MAIN_RISK: 'mainRisk',
  NO_PROPERTIES_AT_RISK: 'noPropertiesAtRisk',
  MAINTAINING_EXISTING_ASSETS: 'maintainingExistingAssets',
  REDUCING_FLOOD_RISK_50_PLUS: 'reducingFloodRisk50Plus',
  REDUCING_FLOOD_RISK_LESS_50: 'reducingFloodRiskLess50',
  INCREASING_FLOOD_RESILIENCE: 'increasingFloodResilience',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK: 'noPropertiesAtCoastalErosionRisk',
  PROPERTIES_BENEFIT_MAINTAINING_ASSETS_COASTAL:
    'propertiesBenefitMaintainingAssetsCoastal',
  PROPERTIES_BENEFIT_INVESTMENT_COASTAL_EROSION:
    'propertiesBenefitInvestmentCoastalErosion',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED: 'percentProperties20PercentDeprived',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED: 'percentProperties40PercentDeprived',
  CURRENT_FLOOD_FLUVIAL_RISK: 'currentFloodFluvialRisk',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'currentFloodSurfaceWaterRisk',
  CURRENT_COASTAL_EROSION_RISK: 'currentCoastalErosionRisk',
  APPROACH: 'approach',
  URGENCY_REASON: 'urgencyReason',
  URGENCY_DETAILS: 'urgencyDetails',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'confidenceHomesBetterProtected',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'confidenceHomesByGatewayFour',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING: 'confidenceSecuredPartnershipFunding',
  ENVIRONMENTAL_BENEFITS: 'environmentalBenefits',
  INTERTIDAL_HABITAT: 'intertidalHabitat',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfIntertidalHabitatCreatedOrEnhanced',
  WOODLAND: 'woodland',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfWoodlandHabitatCreatedOrEnhanced',
  WET_WOODLAND: 'wetWoodland',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfWetWoodlandHabitatCreatedOrEnhanced',
  WETLAND_OR_WET_GRASSLAND: 'wetlandOrWetGrassland',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'hectaresOfWetlandOrWetGrasslandCreatedOrEnhanced',
  GRASSLAND: 'grassland',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfGrasslandHabitatCreatedOrEnhanced',
  HEATHLAND: 'heathland',
  HECTARES_OF_HEATHLAND_CREATED_OR_ENHANCED:
    'hectaresOfHeathlandCreatedOrEnhanced',
  PONDS_LAKES: 'pondsLakes',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfPondOrLakeHabitatCreatedOrEnhanced',
  ARABLE_LAND: 'arableLand',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'hectaresOfArableLandLakeHabitatCreatedOrEnhanced',
  COMPREHENSIVE_RESTORATION: 'comprehensiveRestoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'kilometresOfWatercourseEnhancedOrCreatedComprehensive',
  PARTIAL_RESTORATION: 'partialRestoration',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'kilometresOfWatercourseEnhancedOrCreatedPartial',
  CREATE_HABITAT_WATERCOURSE: 'createHabitatWatercourse',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'kilometresOfWatercourseEnhancedOrCreatedSingle',
  NFM_SELECTED_MEASURES: 'nfmSelectedMeasures',
  NFM_RIVER_RESTORATION_AREA: 'nfmRiverRestorationArea',
  NFM_RIVER_RESTORATION_VOLUME: 'nfmRiverRestorationVolume',
  NFM_LEAKY_BARRIERS_VOLUME: 'nfmLeakyBarriersVolume',
  NFM_LEAKY_BARRIERS_LENGTH: 'nfmLeakyBarriersLength',
  NFM_LEAKY_BARRIERS_WIDTH: 'nfmLeakyBarriersWidth',
  NFM_OFFLINE_STORAGE_AREA: 'nfmOfflineStorageArea',
  NFM_OFFLINE_STORAGE_VOLUME: 'nfmOfflineStorageVolume',
  NFM_WOODLAND_AREA: 'nfmWoodlandArea',
  NFM_HEADWATER_DRAINAGE_AREA: 'nfmHeadwaterDrainageArea',
  NFM_RUNOFF_MANAGEMENT_AREA: 'nfmRunoffManagementArea',
  NFM_RUNOFF_MANAGEMENT_VOLUME: 'nfmRunoffManagementVolume',
  NFM_SALTMARSH_AREA: 'nfmSaltmarshArea',
  NFM_SALTMARSH_LENGTH: 'nfmSaltmarshLength',
  NFM_SAND_DUNE_AREA: 'nfmSandDuneArea',
  NFM_SAND_DUNE_LENGTH: 'nfmSandDuneLength',
  NFM_LAND_USE_CHANGE: 'nfmLandUseChange',
  NFM_ENCLOSED_ARABLE_FARMLAND_BEFORE: 'nfmEnclosedArableFarmlandBefore',
  NFM_ENCLOSED_ARABLE_FARMLAND_AFTER: 'nfmEnclosedArableFarmlandAfter',
  NFM_ENCLOSED_LIVESTOCK_FARMLAND_BEFORE: 'nfmEnclosedLivestockFarmlandBefore',
  NFM_ENCLOSED_LIVESTOCK_FARMLAND_AFTER: 'nfmEnclosedLivestockFarmlandAfter',
  NFM_ENCLOSED_DAIRYING_FARMLAND_BEFORE: 'nfmEnclosedDairyingFarmlandBefore',
  NFM_ENCLOSED_DAIRYING_FARMLAND_AFTER: 'nfmEnclosedDairyingFarmlandAfter',
  NFM_SEMI_NATURAL_GRASSLAND_BEFORE: 'nfmSemiNaturalGrasslandBefore',
  NFM_SEMI_NATURAL_GRASSLAND_AFTER: 'nfmSemiNaturalGrasslandAfter',
  NFM_WOODLAND_LAND_USE_BEFORE: 'nfmWoodlandLandUseBefore',
  NFM_WOODLAND_LAND_USE_AFTER: 'nfmWoodlandLandUseAfter',
  NFM_MOUNTAIN_MOORS_AND_HEATH_BEFORE: 'nfmMountainMoorsAndHeathBefore',
  NFM_MOUNTAIN_MOORS_AND_HEATH_AFTER: 'nfmMountainMoorsAndHeathAfter',
  NFM_PEATLAND_RESTORATION_BEFORE: 'nfmPeatlandRestorationBefore',
  NFM_PEATLAND_RESTORATION_AFTER: 'nfmPeatlandRestorationAfter',
  NFM_RIVERS_WETLANDS_FRESHWATER_BEFORE: 'nfmRiversWetlandsFreshwaterBefore',
  NFM_RIVERS_WETLANDS_FRESHWATER_AFTER: 'nfmRiversWetlandsFreshwaterAfter',
  NFM_COASTAL_MARGINS_BEFORE: 'nfmCoastalMarginsBefore',
  NFM_COASTAL_MARGINS_AFTER: 'nfmCoastalMarginsAfter',
  NFM_LANDOWNER_CONSENT: 'nfmLandownerConsent',
  NFM_EXPERIENCE_LEVEL: 'nfmExperienceLevel',
  NFM_PROJECT_READINESS: 'nfmProjectReadiness',
  IS_LEGACY: 'isLegacy',
  IS_REVISED: 'isRevised',
  WLC_ESTIMATED_WHOLE_LIFE_PV_COSTS: 'wlcEstimatedWholeLifePvCosts',
  WLC_ESTIMATED_DESIGN_CONSTRUCTION_COSTS:
    'wlcEstimatedDesignConstructionCosts',
  WLC_ESTIMATED_RISK_CONTINGENCY_COSTS: 'wlcEstimatedRiskContingencyCosts',
  WLC_ESTIMATED_FUTURE_COSTS: 'wlcEstimatedFutureCosts'
}
