export const PROJECT_VALIDATION_MESSAGES = {
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_OUT_OF_RANGE: 'FINANCIAL_START_YEAR_OUT_OF_RANGE',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_OUT_OF_RANGE: 'FINANCIAL_END_YEAR_OUT_OF_RANGE',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_OUTSIDE_FINANCIAL_RANGE: 'DATE_OUTSIDE_FINANCIAL_RANGE',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_OBC_START: 'DATE_AFTER_OBC_START',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID',
  FAILED_TO_UPLOAD_FILE: 'FAILED_TO_UPLOAD_FILE',
  RISKS_REQUIRED: 'RISKS_REQUIRED',
  RISKS_INVALID: 'RISKS_INVALID',
  MAIN_RISK_REQUIRED: 'MAIN_RISK_REQUIRED',
  MAIN_RISK_INVALID: 'MAIN_RISK_INVALID',
  PROPERTY_VALUE_INVALID: 'PROPERTY_VALUE_INVALID',
  APPROACH_REQUIRED: 'APPROACH_REQUIRED',
  APPROACH_MAX_LENGTH: 'APPROACH_MAX_LENGTH',
  URGENCY_REASON_REQUIRED: 'URGENCY_REASON_REQUIRED',
  URGENCY_REASON_INVALID: 'URGENCY_REASON_INVALID',
  URGENCY_DETAILS_REQUIRED: 'URGENCY_DETAILS_REQUIRED',
  URGENCY_DETAILS_MAX_LENGTH: 'URGENCY_DETAILS_MAX_LENGTH',
  CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED',
  CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID',
  ENVIRONMENTAL_BENEFITS_REQUIRED: 'ENVIRONMENTAL_BENEFITS_REQUIRED',
  ENVIRONMENTAL_BENEFITS_INVALID: 'ENVIRONMENTAL_BENEFITS_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED',
  ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_MIN: 'ENVIRONMENTAL_BENEFITS_QUANTITY_MIN',
  ENVIRONMENTAL_BENEFITS_QUANTITY_PRECISION:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_PRECISION',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_REQUIRED:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_REQUIRED',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_INVALID:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_INVALID',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_REQUIRED:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_REQUIRED',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_INVALID:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_INVALID',
  CURRENT_FLOOD_FLUVIAL_RISK_REQUIRED: 'CURRENT_FLOOD_FLUVIAL_RISK_REQUIRED',
  CURRENT_FLOOD_FLUVIAL_RISK_INVALID: 'CURRENT_FLOOD_FLUVIAL_RISK_INVALID',
  CURRENT_FLOOD_SURFACE_WATER_RISK_REQUIRED:
    'CURRENT_FLOOD_SURFACE_WATER_RISK_REQUIRED',
  CURRENT_FLOOD_SURFACE_WATER_RISK_INVALID:
    'CURRENT_FLOOD_SURFACE_WATER_RISK_INVALID',
  CURRENT_COASTAL_EROSION_RISK_REQUIRED:
    'CURRENT_COASTAL_EROSION_RISK_REQUIRED',
  CURRENT_COASTAL_EROSION_RISK_INVALID: 'CURRENT_COASTAL_EROSION_RISK_INVALID',
  NFM_SELECTED_MEASURES_REQUIRED: 'NFM_SELECTED_MEASURES_REQUIRED',
  NFM_SELECTED_MEASURES_INVALID: 'NFM_SELECTED_MEASURES_INVALID',
  NFM_LANDOWNER_CONSENT_REQUIRED: 'NFM_LANDOWNER_CONSENT_REQUIRED',
  NFM_LANDOWNER_CONSENT_INVALID: 'NFM_LANDOWNER_CONSENT_INVALID',
  NFM_EXPERIENCE_LEVEL_REQUIRED: 'NFM_EXPERIENCE_LEVEL_REQUIRED',
  NFM_EXPERIENCE_LEVEL_INVALID: 'NFM_EXPERIENCE_LEVEL_INVALID',
  NFM_PROJECT_READINESS_REQUIRED: 'NFM_PROJECT_READINESS_REQUIRED',
  NFM_PROJECT_READINESS_INVALID: 'NFM_PROJECT_READINESS_INVALID'
}

export const PROJECT_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR'
}

export const PROJECT_VIEW_ERROR_CODES = {
  ...PROJECT_VALIDATION_MESSAGES,
  ...PROJECT_ERROR_CODES
}
